# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    container_name: natrave-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: natrave